export const mockBlogs = [
  {
    id: '1',
    title: 'The Future of Web Development: What to Expect in 2025',
    slug: 'future-web-development-2025',
    excerpt: 'Explore the upcoming trends and technologies that will shape the web development landscape in 2025 and beyond.',
    coverImage: 'https://images.pexels.com/photos/11035471/pexels-photo-11035471.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: 'Technology',
    createdAt: new Date('2023-12-15'),
    readTime: 8,
    author: {
      name: 'Alex Johnson',
      image: 'https://i.pravatar.cc/150?u=alex@example.com',
    },
    stats: {
      likes: 234,
      comments: 42,
      views: 5678,
    },
  },
  {
    id: '2',
    title: 'Mastering TypeScript: Advanced Tips and Tricks',
    slug: 'mastering-typescript-advanced-tips',
    excerpt: 'Take your TypeScript skills to the next level with these advanced techniques and lesser-known features.',
    coverImage: 'https://images.pexels.com/photos/4164418/pexels-photo-4164418.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: 'Programming',
    createdAt: new Date('2023-11-28'),
    readTime: 12,
    author: {
      name: 'Maria Garcia',
      image: 'https://i.pravatar.cc/150?u=maria@example.com',
    },
    stats: {
      likes: 187,
      comments: 35,
      views: 4290,
    },
  },
  {
    id: '3',
    title: 'The Ultimate Guide to React Server Components',
    slug: 'ultimate-guide-react-server-components',
    excerpt: 'Learn everything you need to know about React Server Components and how they can improve your application performance.',
    coverImage: 'https://images.pexels.com/photos/11035380/pexels-photo-11035380.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: 'Programming',
    createdAt: new Date('2023-11-20'),
    readTime: 10,
    author: {
      name: 'David Chen',
      image: 'https://i.pravatar.cc/150?u=david@example.com',
    },
    stats: {
      likes: 156,
      comments: 28,
      views: 3754,
    },
  },
  {
    id: '4',
    title: 'Digital Minimalism: Simplifying Your Online Life',
    slug: 'digital-minimalism-simplifying-online-life',
    excerpt: 'Discover how to reduce digital clutter and create a more intentional relationship with technology.',
    coverImage: 'https://images.pexels.com/photos/5082579/pexels-photo-5082579.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: 'Lifestyle',
    createdAt: new Date('2023-11-12'),
    readTime: 7,
    author: {
      name: 'Sarah Wilson',
      image: 'https://i.pravatar.cc/150?u=sarah@example.com',
    },
    stats: {
      likes: 132,
      comments: 24,
      views: 2987,
    },
  },
  {
    id: '5',
    title: 'Building Accessible Web Applications: A Complete Guide',
    slug: 'building-accessible-web-applications',
    excerpt: 'Learn how to create web applications that are accessible to everyone, including people with disabilities.',
    coverImage: 'https://images.pexels.com/photos/5926393/pexels-photo-5926393.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: 'Programming',
    createdAt: new Date('2023-10-30'),
    readTime: 15,
    author: {
      name: 'James Taylor',
      image: 'https://i.pravatar.cc/150?u=james@example.com',
    },
    stats: {
      likes: 219,
      comments: 47,
      views: 5124,
    },
  },
  {
    id: '6',
    title: 'The Science of Productivity: Work Smarter, Not Harder',
    slug: 'science-productivity-work-smarter',
    excerpt: 'Research-backed strategies to boost your productivity and achieve more while working less.',
    coverImage: 'https://images.pexels.com/photos/4065876/pexels-photo-4065876.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: 'Business',
    createdAt: new Date('2023-10-18'),
    readTime: 9,
    author: {
      name: 'Emily Rodriguez',
      image: 'https://i.pravatar.cc/150?u=emily@example.com',
    },
    stats: {
      likes: 178,
      comments: 31,
      views: 4567,
    },
  },
  {
    id: '7',
    title: 'Sustainable Travel: Exploring the World Responsibly',
    slug: 'sustainable-travel-exploring-responsibly',
    excerpt: 'Tips and strategies for minimizing your environmental impact while traveling the world.',
    coverImage: 'https://images.pexels.com/photos/3155666/pexels-photo-3155666.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: 'Travel',
    createdAt: new Date('2023-10-05'),
    readTime: 11,
    author: {
      name: 'Michael Brown',
      image: 'https://i.pravatar.cc/150?u=michael@example.com',
    },
    stats: {
      likes: 145,
      comments: 26,
      views: 3298,
    },
  },
  {
    id: '8',
    title: 'Modern CSS Techniques Every Developer Should Know',
    slug: 'modern-css-techniques-developers',
    excerpt: 'Discover the latest CSS features and techniques that can transform your web development workflow.',
    coverImage: 'https://images.pexels.com/photos/5483071/pexels-photo-5483071.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: 'Programming',
    createdAt: new Date('2023-09-22'),
    readTime: 13,
    author: {
      name: 'Alex Johnson',
      image: 'https://i.pravatar.cc/150?u=alex@example.com',
    },
    stats: {
      likes: 201,
      comments: 38,
      views: 4876,
    },
  },
  {
    id: '9',
    title: 'The Beginner\'s Guide to Mindfulness Meditation',
    slug: 'beginners-guide-mindfulness-meditation',
    excerpt: 'Learn how to start a mindfulness meditation practice and transform your relationship with stress and anxiety.',
    coverImage: 'https://images.pexels.com/photos/3560044/pexels-photo-3560044.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: 'Wellness',
    createdAt: new Date('2023-09-10'),
    readTime: 8,
    author: {
      name: 'Maria Garcia',
      image: 'https://i.pravatar.cc/150?u=maria@example.com',
    },
    stats: {
      likes: 167,
      comments: 29,
      views: 3876,
    },
  },
  {
    id: '10',
    title: 'Building a Personal Brand as a Developer',
    slug: 'building-personal-brand-developer',
    excerpt: 'Strategies for creating a strong personal brand that can advance your career in software development.',
    coverImage: 'https://images.pexels.com/photos/4050290/pexels-photo-4050290.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: 'Career',
    createdAt: new Date('2023-08-28'),
    readTime: 10,
    author: {
      name: 'David Chen',
      image: 'https://i.pravatar.cc/150?u=david@example.com',
    },
    stats: {
      likes: 189,
      comments: 34,
      views: 4123,
    },
  },
  {
    id: '11',
    title: 'The Art of Food Photography: Tips from a Professional',
    slug: 'art-food-photography-professional-tips',
    excerpt: 'Professional techniques for capturing stunning food photos that will elevate your social media presence.',
    coverImage: 'https://images.pexels.com/photos/5702355/pexels-photo-5702355.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: 'Photography',
    createdAt: new Date('2023-08-15'),
    readTime: 9,
    author: {
      name: 'Sarah Wilson',
      image: 'https://i.pravatar.cc/150?u=sarah@example.com',
    },
    stats: {
      likes: 176,
      comments: 32,
      views: 3897,
    },
  },
  {
    id: '12',
    title: 'Understanding Blockchain: Beyond the Hype',
    slug: 'understanding-blockchain-beyond-hype',
    excerpt: 'A straightforward explanation of blockchain technology and its practical applications beyond cryptocurrencies.',
    coverImage: 'https://images.pexels.com/photos/6781348/pexels-photo-6781348.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: 'Technology',
    createdAt: new Date('2023-08-03'),
    readTime: 14,
    author: {
      name: 'James Taylor',
      image: 'https://i.pravatar.cc/150?u=james@example.com',
    },
    stats: {
      likes: 213,
      comments: 45,
      views: 5032,
    },
  },
];

export const mockUser = {
  id: '1',
  name: 'Alex Johnson',
  email: 'alex@example.com',
  image: 'https://i.pravatar.cc/150?u=alex@example.com',
  bio: 'Full-stack developer passionate about creating beautiful and functional web applications.',
  socialLinks: {
    twitter: 'https://twitter.com/alexjohnson',
    github: 'https://github.com/alexjohnson',
    linkedin: 'https://linkedin.com/in/alexjohnson',
  },
  stats: {
    followers: 245,
    following: 128,
    blogs: 15,
  },
};

export const mockComments = [
  {
    id: '1',
    content: 'This is a fantastic article! I learned so much about TypeScript that I didn\'t know before.',
    createdAt: new Date('2023-11-29T10:23:00'),
    author: {
      id: '2',
      name: 'Maria Garcia',
      image: 'https://i.pravatar.cc/150?u=maria@example.com',
    },
    likes: 8,
    replies: [
      {
        id: '1-1',
        content: 'I agree! The section about generics was particularly helpful.',
        createdAt: new Date('2023-11-29T11:05:00'),
        author: {
          id: '3',
          name: 'David Chen',
          image: 'https://i.pravatar.cc/150?u=david@example.com',
        },
        likes: 3,
      },
      {
        id: '1-2',
        content: 'Thanks for your kind words! I\'m glad you found it helpful.',
        createdAt: new Date('2023-11-29T12:30:00'),
        author: {
          id: '1',
          name: 'Alex Johnson',
          image: 'https://i.pravatar.cc/150?u=alex@example.com',
        },
        likes: 2,
      },
    ],
  },
  {
    id: '2',
    content: 'I\'ve been using TypeScript for years and still learned some new tricks from this article. Great job!',
    createdAt: new Date('2023-11-30T09:15:00'),
    author: {
      id: '4',
      name: 'Sarah Wilson',
      image: 'https://i.pravatar.cc/150?u=sarah@example.com',
    },
    likes: 12,
    replies: [],
  },
  {
    id: '3',
    content: 'Do you have any recommendations for TypeScript resources for beginners?',
    createdAt: new Date('2023-12-01T14:45:00'),
    author: {
      id: '5',
      name: 'Michael Brown',
      image: 'https://i.pravatar.cc/150?u=michael@example.com',
    },
    likes: 4,
    replies: [
      {
        id: '3-1',
        content: 'The TypeScript Handbook is a great place to start, and I also recommend the courses on Frontend Masters.',
        createdAt: new Date('2023-12-01T15:20:00'),
        author: {
          id: '1',
          name: 'Alex Johnson',
          image: 'https://i.pravatar.cc/150?u=alex@example.com',
        },
        likes: 7,
      },
    ],
  },
];